### ISSUE TITLE
Ignore reexports in .pyi files for F401

### ISSUE THREAD

**Issue by mkurnikov** [PyCQA/pyflakes#474] opened 2019-09-25 00:23 UTC
Is it possible for flake8 F401 to ignore this kind of re-exports?
https://github.com/typeddjango/django-stubs/blob/master/django-stubs/db/models/__init__.pyi

mypy uses those to be able to discern between imports which could, and which could not be imported from the file.

**Comment by Hanaasagi** [comment] 2019-10-12 08:22
Ref [PEP-484](https://www.python.org/dev/peps/pep-0484/#stub-files):

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form.
> 
> However, as an exception to the previous bullet, all objects imported into a stub using from ... import * are considered exported. (This makes it easier to re-export all objects from a given module that may vary by Python version.)

This rule should only apply on stub files. I'm not sure that it's a good idea to treat them differently.

**Comment by Tinche** [comment] 2020-04-16 22:22
Just ran into this while writing a stub file. IMO F401 is a very useful rule for regular Python files, but useless for stubs (like @mkurnikov explained).

**Comment by asottile** [comment] 2020-04-16 22:31
if you're using flake8, you can leverage `per-file-ignores` to ignore specific codes in pyi files only:

```ini
[flake8]
per-file-ignores =
    *.pyi: F401
```

**Comment by Tinche** [comment] 2020-04-16 22:52
@asottile That's very useful, thank you!

**Comment by jack1142** [comment] 2020-08-30 22:24
IMO, both types of explicit re-exports (one being using `__all__`, and the other one being `import same_name_on_both_sides_of_as as same_name_on_both_sides_of_as`) should be ignored in regular Python files, not just in `.pyi` files.

**Comment by asottile** [comment] 2021-03-22 15:29
the pep states that this should only apply to `.pyi` files -- since pyflakes does not support `.pyi` files I don't think this should be implemented

supporting `.pyi` files would be a different feature request

**Comment by Dreamsorcerer** [comment] 2021-08-08 13:50
This seems like a pretty common practice in `.py` files as well, for example, look at many of the reexported variables in aiohttp (mypy validates these as reexported):
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/__init__.py
https://github.com/aio-libs/aiohttp/blob/3.8/aiohttp/typedefs.py#L21-L26

**Comment by asottile** [comment] 2021-08-08 13:51
you'll notice that no `# noqa`s were necessary in `__init__.py` because they were properly documented [through __all__](https://github.com/aio-libs/aiohttp/blob/3a479d39c8012b842f8f1201e288252b0c9c843e/aiohttp/__init__.py#L106)

**Comment by Dreamsorcerer** [comment] 2021-08-08 13:55
The problem with that approach is that it duplicates everything, so there are now 2 lists of variables to maintain. Using the `as` syntax is a little more maintainable (not sure why we `__all__` as well as `as` actually, might have to clean that up...).

**Comment by asottile** [comment] 2021-08-08 13:58
(not sure why I reopened this, it should have remained closed as pyflakes does not support `.pyi` files)

**Closed** 2021-08-08 13:57 UTC

**Comment by osandov** [comment] 2021-08-11 21:13
I have some cases in `.py` files where I'd like to reexport variables explicitly with `import X as X` but I don't want them to be included in `__all__`. mypy supports this, so it'd be great if pyflakes would consider these used.

**Comment by hauntsaninja** [comment] 2022-08-18 01:10
Hello! While this convention did originate with `.pyi` files, type checkers use redundancy to recognise re-exports in `.py` files as well. I can confirm that at least both of pyright and mypy use this pattern to distinguish the intention of imports in `.py` files.

You may also be interested in this typing-sig thread, where everyone involved seemed to get on the same page about rules for considering modules as re-exported (including `import X as X`):
https://mail.python.org/archives/list/typing-sig@python.org/thread/YLJPWECBNPD2K4TRIBRIPISNUZJCRREY/#LQ3OMFK2OPBUYV7UHYEFGCJPUXQEGM4P

So yes, pyflakes shouldn't support `.pyi` files. For whatever it's worth, I'm a maintainer of flake8-pyi and I'm not looking to upstream any of those checks ;-)

But would you be willing to accept a PR that changes behaviour here given that it's used in `.py` files?

**Comment by asottile** [comment] 2022-08-18 12:07
I'd rather not since it's also a common mistake that I've seen and fixed before type checkers existing -- there's already two methods to silence the pattern (`__all__`, and `noqa`)

**Comment by asottile** [comment] 2022-08-18 13:53
if there was a PEP perhaps it would be an easier argument -- but PEP 484 only indicates that this should be supported in `.pyi`

**Comment by andersk** [comment] 2022-11-13 19:58
Should one expect this convention to have been encoded in a PEP? It needs no special support from the Python language itself or its runtime implementations—as far as those are concerned, *every* import is reexported. Many details of typing have always been left up to checker implementations, such as what kinds and directions of type inference are supported.

**Comment by sigmavirus24** [comment] 2022-11-14 00:23
> Should one expect this convention to have been encoded in a PEP? It needs no special support from the Python language itself or its runtime implementations—as far as those are concerned, *every* import is reexported. 

Many things pyflakes advises against need no special support from the language or implementations. I think there's a difference between "this is an idiom that can hide valid points and has historically been a mistake that people want caught" and "this is an idiom we're suggesting people adopt and codifying in a PEP or some other core document. As it stands now, there are two ways to hide this already. I don't think ignoring it by default is the right choice either. 

> Many details of typing have always been left up to checker implementations, such as what kinds and directions of type inference are supported.

Right, and pyflakes introspects annotations but doesn't need to assume the wrong thing here.

**Comment by hauntsaninja** [comment] 2022-11-14 00:38
Yeah, this isn't the kind of thing that's worth a whole PEP and because PEP 484 is not a living document it probably isn't going to get edited in.

So the typing-sig thread I link to above is about as good as we're going to get for now. We have aspirations to make living documentation of how type checkers are expected to behave in some tool-neutral location like typing.readthedocs.io, but that will take a while. But maybe once that happens it'll be considered official enough to merit a change in pyflakes behaviour! :-)

**Comment by hauntsaninja** [comment] 2022-11-14 00:44
I'm also a little surprised at the claim redundant "as" clause `import X as X` is a common mistake (hasn't really matched my anecdotal experience). I'm curious if you have a sense for what users who use it mistakenly intended to do? If there's some common confusion here maybe I could e.g. improve mypy docs about this :-)

**Comment by sigmavirus24** [comment] 2022-11-14 21:11
> I'm also a little surprised at the claim that the redundant "as" clause `import X as X` is a common mistake (hasn't really matched my anecdotal experience). I'm curious if you have a sense for what users who use it mistakenly intended to do? If there's some common confusion here maybe I could e.g. improve mypy docs about this :-)

My experience predates mypy's existence and the widespread use of type annotations, so keep that context in mind. In my experience, it was often _a_ mistake (not something people intentionally wrote as `import X as X`) that occurred during some refactor/clean-up/something else and an inattentive developer missed it.

These were usually very large code-bases. Usually, looking at the history the developer was confused and added a `# noqa` to the line at the same time they changed the import.  I can't explain the reasoning those developers had. I just came in after the fact, saw something phishy and "fixed" it (after verifying it wasn't intended to be re-exported).
