### ISSUE TITLE
Unhandled exception in pyflakes (python 3.8)

### ISSUE THREAD

**Issue by lukas-manduch** [PyCQA/pyflakes#504] opened 2020-01-10 15:46 UTC
Hey guys, while using pyflakes in my project I found out, that it crashes on new python 3.8 code (probably due to Assignment Expressions).  I know 3.8 is not supported, but imo it shouldn't crash anyway. 
Pyflakes 2.1.1 

Source code:
```
import re

pattern = r'^\s*'
line = ''
if not (match := re.match(pattern, line)):
    exit(1)
```
Exception:
```
(testscripts2) PS C:\Users\lukas.manduch\source\repos\testscripts> pyflakes.exe --version
2.1.1 Python 3.8.0 on Windows
(testscripts2) PS C:\Users\lukas.manduch\source\repos\testscripts> pyflakes.exe C:\Users\lukas.manduch\evaluators.py
Traceback (most recent call last):
  File "C:\Users\lukas.manduch\.pyenv\pyenv-win\versions\3.8.0-amd64\Lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lukas.manduch\.pyenv\pyenv-win\versions\3.8.0-amd64\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lukas.manduch\source\virtualenvs\testscripts2\Scripts\pyflakes.exe\__main__.py", line 7, in <module>
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\api.py", line 207, in main
    warnings = checkRecursive(args, reporter)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\api.py", line 156, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "c:\users\lukas.manduch\source\virtualenvs\testscripts2\lib\site-packages\pyflakes\checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'NAMEDEXPR'
````

**Comment by asottile** [comment] 2020-01-10 15:51
duplicate of #457 (already fixed)

**Closed by asottile** 2020-01-10 15:51 UTC
