### ISSUE TITLE
F811 (redefinition of unused variable) incorrectly triggered with @t.overload decorator

### ISSUE THREAD

**Issue by Pagliacii** [PyCQA/pyflakes#626] opened 2021-03-25 10:52 UTC
I have searched issues and found a similar one #434. It could be shown that pyflakes support the `@overload` decorator. And I can pass the check if I'm using `@overload`. But if I used `@t.overload` rather than `@overload`, pyflakes has complained about an F811 warning.

Here is my test code:

```python
import typing as t

@t.overload
def add(a: int, b: int) -> int:
    ...


@t.overload
def add(a: str, b: str) -> str:
    ...


def add(a, b):
    return a + b
```

I am using the 2.3.1 version pyflakes.

**Comment by asottile** [comment] 2021-03-25 14:08
dupe of #561

**Closed by asottile** 2021-03-25 14:08 UTC
