### ISSUE TITLE
redefinition of unused 'range' from line (flake8 F811) false positive

### ISSUE THREAD

**Issue by peterjc** [PyCQA/pyflakes#430] opened 2019-02-13 15:59 UTC
This could be related to #372 which describes a similar false positive.

Example test case, ``fp.py`` (false positive):

```python
"""This is a test case for flake8 or pyflakes."""

from builtins import range  # noqa: F401


class Wibble(object):
    """Simple object holding a list or array of values."""

    def __init__(self, values):
        """Create object."""
        self.values = values

    def range(self):
        """Return min/max of the values."""
        return min(self.values), max(self.values)


w = Wibble([1, 2, 3, 4, 5])
assert w.range() == (1, 5)
```

Usage:

```
$ python3 --version
Python 3.7.0rc1
$ python3 fp.py
```

With flake8 I can disable the unused import, leaving just the false positive F811

```
$ flake8 --version
3.6.0 (black: 0.0.1, flake8-bugbear: 18.2.0, flake8-docstrings: 1.3.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0, rst-docstrings: 0.0.8) CPython 3.7.0rc1 on Darwin
$ flake8 fp.py
fp.py:13:5: F811 redefinition of unused 'range' from line 3
```

Running pyflakes directly,

```
$ pyflakes --version
2.0.0
$ pyflakes fp.py
fp.py:3: 'builtins.range' imported but unused
fp.py:13: redefinition of unused 'range' from line 3
```

This test case was based on https://github.com/biopython/biopython/commit/78a73b99856b92327ecfef632781f0f5fde0f5d3 and the preceding commit, where I was importing  a ``range`` function from a compatibility library, and had a class defining an unrelated ``range`` method.

**Comment by asottile** [comment] 2019-08-08 19:55
Duplicate of #268

**Closed by asottile** 2019-08-08 19:55 UTC
