### ISSUE TITLE
detect as unused imports subsumed by other imports

### ISSUE THREAD

**Issue by graingert** [PyCQA/pyflakes#513] opened 2020-02-18 09:17 UTC
*Please describe how you installed Flake8*

```
pip install flake8==3.7.9 pyflakes==2.1.1
```

```python
import sqlalchemy  # should be detected as unused
import sqlalchemy.exc


try:
    pass
except sqlalchemy.exc.DatabaseError:
    pass
```

**Comment by asottile** [comment] 2020-02-18 15:43
this is a duplicate of #429 / #137 (and a few others but those were the ones I could find quickly on my phone)

**Closed by asottile** 2020-02-18 15:43 UTC
