### ISSUE TITLE
F841 false positive in async for

### ISSUE THREAD

**Issue by Behoston** [PyCQA/pyflakes#307] opened 2017-10-18 07:55 UTC
in venv
```bash
pip install flake8
```

```python
async def x(y):
    async for _ in y:
        pass

```
produces: 
>  F841 local variable '_' is assigned to but never used

but not-async works fine 
```python
async def x(y):
    for _ in y:
        pass
```

**Comment by myint** [comment] 2017-10-19 01:42
This is a duplicate of #304.

**Closed by myint** 2017-10-19 01:42 UTC
