### ISSUE TITLE
F811 (redefinition of unused variable) still incorrectly triggered with @<alias-of-typing>.overload

### ISSUE THREAD

**Issue by flying-sheep** [PyCQA/pyflakes#592] opened 2020-11-11 13:42 UTC
#320 is still not fully fixed. F811 still gets erroneously triggered. You need to actually resolve the module instead of relying on the alias happening to be “typing” or “typing_entensions”

```py
import typing as t

class C:
	@t.overload
	def ...
	@t.overload
	def ...

	def ...
```

**Comment by asottile** [comment] 2020-11-11 16:59
dupe of #561

**Closed by asottile** 2020-11-11 16:59 UTC
