### ISSUE TITLE
Not reporting "a" as unused variable in "for a in [1]: print(1)"

### ISSUE THREAD

**Issue by dilyanpalauzov** [PyCQA/pyflakes#296] opened 2017-09-20 12:57 UTC
```python
def x():
  for a, b in [(1,2)]: print(a)
```

`pyflakes` does not report `b` as unused variable

**Comment by myint** [comment] 2017-09-20 13:17
This looks like a duplicate of #143 and #285.

**Closed by myint** 2017-09-20 13:17 UTC
