### ISSUE TITLE
Does not detect used/unused modules within packages

### ISSUE THREAD

**Issue by csilvers** [PyCQA/pyflakes#288] opened 2017-08-26 20:45 UTC
pyflakes does not raise any errors on the following code:
```
import foo.bar
import foo.baz

foo.bar.fn()
foo.bang.fn()
```
despite the fact that `foo.baz` is an unused import, and `foo.bang` is not imported at all.

Is this behavior intentional?  Is there a way to modify pyflakes so it would warn in (ideally) both cases?

Thanks,
craig

**Comment by myint** [comment] 2017-08-27 19:29
This looks like a duplicate of #137.

**Closed by myint** 2017-08-27 19:29 UTC
Labels: duplicate

**Comment by csilvers** [comment] 2017-08-27 20:17
You're right! And I thought I was so careful looking through old bug reports...
