### ISSUE TITLE
expression in annotation is not correctly handled.

### ISSUE THREAD

**Issue by thy09** [PyCQA/pyflakes#646] opened 2021-07-05 08:21 UTC
We are implementing a feature that allow a user to describe his parameter for a python function.
The code is like this:
```python
class StringParameter:
    def __init__(self, description=None):
        self._description = description


def my_func(
    param: StringParameter(description="This is a param.")
):
    pass
```

However, this code will hit F722 error: syntax error in forward annotation

I have checked the code, the problem is that all strings in an annotation is expected to be a valid ast node.
https://github.com/PyCQA/pyflakes/blob/da197ee94e791640d82940396c19d2d82ca8defb/pyflakes/checker.py#L1460

I guess we have this rule since we need to handle the case like `param: Mapping[str, 'SomeClass']`.

But in my scenario, an arbitrary string could be in the annotation.
Now I need to workaround like this:
```python
string_param_annotation = StringParameter(description="This is a param.")

def my_func(
    param: string_param_annotation,
):
    pass
```

It would be good if we could optimize the annotation handling logic to avoid this problem.
Thanks a lot!

**Comment by sigmavirus24** [comment] 2021-07-05 11:46
Duplicate of #554 as best as I can tell

**Closed by sigmavirus24** 2021-07-05 11:46 UTC

**Comment by thy09** [comment] 2021-07-06 03:32
Hi @sigmavirus24 
I understand that an arbitrary complex annotation like #554 is not included in PEP484.
But what I want to do is more like this:
```
from typing import TypeVar

class StringParameter(TypeVar):

    def __init__(self, name, description):
        self._description=description
        TypeVar.__init__(self, name, str, bytes)

def my_func(
    param0: StringParameter(name="StringType0", description="String Type 0"),
    param1: TypeVar("StringType1", str, bytes),
):
    print(param0)
    print(param1)

```

Then this line `TypeVar("StringType1", str, bytes)` has no error,
while the other lines show "**syntax error in forward annotation 'String Type 0'**" and "**undefined name 'StringType0'**".

According to the description in [PEP484](https://www.python.org/dev/peps/pep-0484/#acceptable-type-hints),
"**Annotations must be valid expressions that evaluate without raising exceptions at the time the function is defined**"

I think my code is following PEP 484.
Maybe it is hard for type checking in static analysis,
but I think at least we could avoid errors on this kind of annotation?
What's your opinion?
Thanks a lot!

**Comment by sigmavirus24** [comment] 2021-07-06 11:07
We only support 484-style annotations. Theoretically, Python supports exactly what you're doing but it's not the most common usage. Three largest group of annotation users is going to be 484/mypy users and your use case does not fit with those.

**Comment by thy09** [comment] 2021-07-07 03:25
Thanks @sigmavirus24 
I agree that this is not a common usage in 484.

So I think I need to ask 484 maintainers what is the suggested usage in the future to add properties for a TypeVar.
Do you know where could I ask such questions?
Thanks a lot!

**Comment by asottile** [comment] 2021-07-07 12:43
The typing-sig mailing list is probably your best bet -- though `TypeVar` isn't meant to be a runtime concept so I suspect they will just tell you that https://mail.python.org/archives/list/typing-sig@python.org/

**Comment by thy09** [comment] 2021-07-08 02:35
Got it, thanks a lot!
