### ISSUE TITLE
F722 raised when import alias used for typing.Annotated

### ISSUE THREAD

**Issue by Hawkpath** [PyCQA/pyflakes#638] opened 2021-05-26 03:30 UTC
Hey there. I am using `typing.Annotated` ([PEP 593](https://www.python.org/dev/peps/pep-0593/)) to add metadata to type annotations, and I'm importing it with an alias. I'm not sure if aliasing these special typing annotations is supported behavior, but pyflakes (2.3.1) is not liking it.

No errors:
```python
from typing import Annotated

class Test:
    field: Annotated[str, '%hello']
```

Raises F722:
```python
from typing import Annotated as Ann

class Test:
    field: Ann[str, '%hello']
```

Note that this fails because `'%hello'` is interpreted as a forward reference which is an invalid Python identifier, when it's actually annotation metadata which is a normal Python expression.

PyCharm and `typing.get_type_hints` correctly follow the alias which leads me to believe this is supported, but I can't find anything related to this in the PEP.

If anyone else has this problem, the solution is to use the full name `Annotated` rather than an alias.

**Comment by asottile** [comment] 2021-05-26 03:35
dupe of #561

**Closed by asottile** 2021-05-26 03:35 UTC
