### ISSUE TITLE
Undefined name error for unimported type hints written as string

### ISSUE THREAD

**Issue by xiamaz** [PyCQA/pyflakes#340] opened 2018-07-07 10:18 UTC
PEP484 explicitly allows unimported types to be specified as a string. pyflakes 2.0.0 tries to parse these strings and is unable to find the correct typedefs and reports an unexpected error.

```
def hello(a: "Unknown") -> str:
    return str(a)
```

generates the pyflakes error

```
foo.py:1: undefined name 'Unknown'
```

**Comment by sigmavirus24** [comment] 2018-12-05 23:57
@PetterS I don't understand your comment "This has to be a pyflakes bug."

**Comment by asottile** [comment] 2018-12-30 21:12
This issue is invalid as far as I can tell.  The only place PEP 484 mentions string literals is in the [forward references](https://www.python.org/dev/peps/pep-0484/#forward-references) section.

The important bits from this:

> The string literal should contain a valid Python expression (i.e.,` compile(lit, '', 'eval')` should be a valid code object) and it should **evaluate without errors once the module has been fully loaded**. 

(emphasis mine)

When forward references are used correctly, pyflakes does not produce an error:

```
def f() -> 'Wat': pass
class Wat: pass
```

**Comment by asottile** [comment] 2018-12-30 21:39
as far as I understand, PEP484 replaces the lack of guidance in PEP3107 (from [the abstract](https://www.python.org/dev/peps/pep-0484/#abstract)):

> PEP 3107 introduced syntax for function annotations, but the semantics were deliberately left undefined. There has now been enough 3rd party usage for static type analysis that the community would benefit from a standard vocabulary and baseline tools within the standard library.

This issue as written is about PEP484 type annotations and is invalid, the suggestion you're making is a duplicate of #373 which I believe is also invalid according to the first paragraph of PEP 484

**Comment by C0DK** [comment] 2019-07-15 12:26
is anything done to fix this?

I currently use typing however cannot import the annotated type as it will give a circular import creating a whole new range of bugs. That might be a symbol of some bad software design on my end (not sure) but it's problematic to add NOQA to multiple function definitions in my django application

**Comment by asottile** [comment] 2019-07-15 13:54
Can you use the mypy only import?

```python
if False:  # or typing.TYPE_CHECKING  if python3.5.3+
    from ...
```

Though circular imports are often an indication of a design problem

**Comment by asottile** [comment] 2019-07-15 13:54
Also this issue is about non pep-484 annotations, I don't think your import cycle is the same problem

**Comment by C0DK** [comment] 2019-07-16 07:48
@asottile 
An example could be:
`def get_upcoming_deposits(self, user: "accounts.models.User"):  # noqa: F821`

the manager of the Deposit model has a helper function for getting all upcoming deposits. typing wise they are possibly rather tightly knitted. maybe i should just move some function and figure out how i can do with out the circular typing dependencies.

**Comment by asottile** [comment] 2019-07-16 15:39
yeah different problem, please create a new issue

**Comment by C0DK** [comment] 2019-07-20 12:41
isn't it the exact same problem? i am using annotations as permitted by PEP 3107.  and the typing should be able to handle a external reference IMO. 

the PEP you reference even says:

>Note that this PEP still explicitly does NOT prevent other uses of annotations, nor does it require (or forbid) any particular processing of annotations, even when they conform to this specification. It simply enables better coordination, as PEP 333 did for web frameworks.

However if the consensus is that it's simply due to shitty code by my hand, then I'll take the error as a design flaw by me and try to redesign that aspect.

**Comment by asottile** [comment] 2019-07-20 14:36
@C0DK can you show an actual full code example?  your sample looks like a PEP 484 annotation, and in fact pyflakes is fine with what you have:

```python
import accounts.models

def get_upcoming_deposits(self, user: "accounts.models.User"): ...
```

```console
$ pyflakes t.py
$
```

**Comment by C0DK** [comment] 2019-07-22 13:15
the thing is that i cannot import accounts.models, as i will get a circular import. so that line is essentially everything. at runtime the type exists though, as the file containing the `get_upcoming_deposits` is being imported by account.models.. which is probably where my design flaw originates :P

**Comment by asottile** [comment] 2019-07-22 14:43
what about the usual "import for type annotations" approach:

```python
if False:  # if typing.TYPE_CHECKING if you don't care about 3.5.0 / 3.5.1
    import accounts.models

def get_upcoming_deposits(self, user: "accounts.models.User"): ...
```

**Comment by C0DK** [comment] 2019-07-30 13:21
that could work. Thank you :)

**Comment by asottile** [comment] 2019-09-30 21:58
to the original issue, from [PEP 563](https://www.python.org/dev/peps/pep-0563/#rationale-and-goals):

> In Python 3.8 PEP 484 will graduate from provisional status. Other enhancements to the Python programming language like PEP 544, PEP 557, or PEP 560, are already being built on this basis as they depend on type annotations and the typing module as defined by PEP 484. In fact, the reason PEP 484 is staying provisional in Python 3.7 is to enable rapid evolution for another release cycle that some of the aforementioned enhancements require.
>
> With this in mind, uses for annotations incompatible with the aforementioned PEPs should be considered deprecated.

given the official stance that annotations incompatible with the typing peps are deprecated closing this as invalid -- thanks again for the issue!

**Closed by asottile** 2019-09-30 21:58 UTC
