### ISSUE TITLE
Error when referencing a class yet not declared inside function

### ISSUE THREAD

**Issue by hugowschneider** [PyCQA/pyflakes#749] opened 2022-11-25 16:42 UTC
I am facing a bug.

I created this example to test all behaviours I can foresee and spotted a bug:

```python
from typing import Optional

class InnerModel1:
        model2: "Model2"
        mode2_no_err1: Optional["Model2"] # NO ERROR
        mode2_no_err2: "Optional[Model2]" # NO ERROR

class Model2:
    pass

def f():
    class InnerModel1:
        model2: "InnerModel2"
        mode2_err: Optional["InnerModel2"] # ERROR
        mode2_no_err: "Optional[InnerModel2]"

    class InnerModel2:
        pass
```
if I run `pyflakes` against this code I get:

`pyflakes_bug.py:14:29: undefined name 'InnerModel2'`

I would expect that annotating a with `Optional["InnerModel2"]` or with `"Optional[InnerModel2]"` should have the same behaviour as demonstrated with `Optional["Model2"]` and `"Optional[Model2]"`.

Why am I defining a class inside a method?  For now this is supporting lots of unit testing on my side.

**Comment by sigmavirus24** [comment] 2022-11-25 18:03
Did you test if mypy complains about this with `--strict`? My suspicion (I'm on a phone, unable to test myself) is that it will.

**Comment by hugowschneider** [comment] 2022-11-25 19:52
`mypy --strict` only complains that `f()` has not return values defined. So if I do

```python
from typing import Optional

class InnerModel1:
        model2: "Model2"
        mode2_no_err1: Optional["Model2"] # NO ERROR
        mode2_no_err2: "Optional[Model2]" # NO ERROR

class Model2:
    pass

def f() -> None:
    class InnerModel1:
        model2: "InnerModel2"
        mode2_err: Optional["InnerModel2"] # ERROR
        mode2_no_err: "Optional[InnerModel2]"

    class InnerModel2:
        pass
```

mypy does not complain about anything anymore.

---------

I forgot to mention the versions before:

```sh
$ pyflakes --version
2.5.0 Python 3.8.15 on Linux
```

```sh
$ mypy --version
mypy 0.971 (compiled: no)
```

**Comment by sigmavirus24** [comment] 2022-11-25 22:57
Pyflakes 3.0 just came out, can you confirm this isn't still present on that version?

**Comment by hugowschneider** [comment] 2022-11-26 08:17
No changes with pyflakes 3.0.1

```sh
$ pyflakes pyflakes_bug.py 
pyflakes_bug.py:14:29: undefined name 'InnerModel2'
$ pyflakes --version      
3.0.1 Python 3.8.15 on Linux
```

**Comment by asottile** [comment] 2022-11-27 19:47
if you set `from __future__ import annotations` then it works -- I think this has something to do with the weird class scopes (they're not true scopes)

**Comment by asottile** [comment] 2022-11-27 20:01
yeah this is very tricky to fix without the `annotations` behaviour.

basically pyflakes has a concept of "deferred" evalutation to check dead scopes, annotations, and unused assignments

the problem is a function scope is itself already deferred (since it needs to check its closure scope) and that implementation is a little conflated with the deferred annotations checking -- currently if it's already in a deferred state it just evaluates it immediately

I *think* this could be fixed by making the "deferred" checking a queue instead?

**Closed** 2022-11-27 20:36 UTC
