### ISSUE TITLE
Unused imports not reported if they are in a hierarchy

### ISSUE THREAD

**Issue by timj** [PyCQA/pyflakes#429] opened 2019-02-12 19:36 UTC
I would really expect this code to issue an F401 warning:
```python
import collections
import collections.abc

a = collections.OrderedDict()
```
since `collections.abc` is imported but unused. Unfortunately pyflakes doesn't think there is a problem and it seems that using anything from a package hierarchy quietens the warning.

We have noticed this in our project where we have lots of independent packages but we keep them in a shared root namespace (project `a` with independent packages `a.b` and `a.c.d`). We recently noticed that pyflakes is ignoring all the unused imports we have in the code because they are all in `a`.

**Comment by asottile** [comment] 2019-02-12 19:44
Have to be [very careful](https://github.com/asottile/scratch/wiki/ImportSideEffects) here

The only "safe" to mark as unused is the `import collections`  line (which https://github.com/asottile/reorder_python_imports will auto-remove fwiw)

**Comment by timj** [comment] 2019-02-12 19:51
I was trying to show some code that is reproducible in native python without dependencies. In our case it's clearer because we do:

```python
import lsst.afw.image
import lsst.daf.butler

img = lsst.afw.image.Exposure("xxx.fits")
```
and pyflakes thinks this is fine even thought the two imports come from completely different packages with no weird imports (I had also forgotten that even if you don't have our code, pyflakes doesn't care). Changing the code to:

```python
import lsst.afw.image
import lsstx.daf.butler

img = lsst.afw.image.Exposure("xxx.fits")
```
Does trigger `xxx.py:2: 'lsstx.daf.butler' imported but unused`.  This seems very wrong.

As for my original example, if I change it to:
```python
import collections.abc

a = collections.OrderedDict()
```
then the code is completely broken:
```
Traceback (most recent call last):
  File "../flaketest.py", line 4, in <module>
    import collections.abc
ImportError: No module named abc
```
but pyflakes thinks everything is fine.

**Comment by asottile** [comment] 2019-02-12 20:02
Your sample works fine in python3. pyflakes does not import your code or do any dynamic analysis (and also has no options and leans very heavily towards no false positives).

The root of your issue is that both `import a.b.c` and `import a.c.d` _only cause the `a` symbol to be introduced_

I actually linked the wrong page before, this is the one I meant to: https://github.com/asottile/scratch/wiki/Why-doesn't-flake8-mark-this-as-an-unused-import%3F

**Comment by timj** [comment] 2019-02-12 20:08
My original sample code does work in Python 3 (I only use python 3). I was confused when you told me to remove the `import collections` (that can't work but pyflakes has no comment).  Thanks for the link. That's extremely disappointing considering that namespace packages were meant to be a great feature for python 3.

**Comment by SimonKrughoff** [comment] 2019-02-12 20:42
Thanks for the link to the post explaining the issue.  To me it seems like the reasoning should be reversed.  Most of the time it's quite reasonable to warn about an unused import (even if it shares part of a namespace with another import that is used).  In the case where the import is made purely for side effect reasons, it seems ok to require an explicit exception precisely because it is so evil (as your post points out).

**Comment by asottile** [comment] 2019-08-08 19:55
Duplicate of #137

**Closed by asottile** 2019-08-08 19:55 UTC
