### ISSUE TITLE
pyflakes misses an undefined variable (F821) when a variable is defined in an outer scope, but not in time

### ISSUE THREAD

**Issue by alexwlchan** [PyCQA/pyflakes#807] opened 2024-03-25 23:00 UTC
Consider the following code:

```python
# example.py
def my_function():
    return result


result = my_function()
print(result)
```

Both pyflakes 3.2.0 and main commit c68ed1b (latest at time of writing) report no issues with this file:

```console
$ pyflakes --version
3.2.0 Python 3.12.0 on Darwin
$ pyflakes s.py
$ echo "$?"
0
```

But if you actually try to run this code, it fails immediately:

```console
$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    result = my_function()
             ^^^^^^^^^^^^^
  File "example.py", line 2, in my_function
    return result
           ^^^^^^
NameError: name 'result' is not defined
```

I was slightly surprised that flake8/pyflakes didn't warn me about the undefined variable (F821) at the end of `my_function`.

This is a reduced example of a bug I encountered in some real code, where a function was returning a variable `result` that shadowed the name of the variable being used to capture the output of the function.

I can see this is a bit of a pathological edge case that would be tricky to hit in practice, and I can see why it might be very difficult to find this with static analysis without actually running the code. But I figured it might be useful to flag just in case.

**Comment by sigmavirus24** [comment] 2024-03-26 00:05
Pretty sure this is a duplicate of #236

**Comment by sigmavirus24** [comment] 2024-03-26 00:06
And yes, this is one of those cases where the way in which nodes and contexts are processed make it hard to detect this without a high rate of false positives

**Comment by asottile** [comment] 2024-03-26 01:05
yep, to pyflakes that _could_ be valid and so it does not flag it (it doesn't know that your module scope is side-effects)

**Closed by asottile** 2024-03-26 01:05 UTC

**Comment by alexwlchan** [comment] 2024-03-26 06:11
Makes sense, thanks for explaining!
