### ISSUE TITLE
Typing.TYPE_CHECKING imports raise F401

### ISSUE THREAD

**Issue by henryJack** [PyCQA/pyflakes#290] opened 2017-09-07 12:44 UTC
```
$ pip install  flake8

```

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from my_module.test_class import MyClass

object: 'MyClass' = None
```
Flake 8 gives the following error in this scenario:

`my_module\test_class.py:4:5: F401 'my_module.test_class.MyClass' imported but unused`

My current work around is this:

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from my_module.test_class import MyClass  # noqa

object: 'MyClass' = None
```

Any better solutions? Couldwe somehow automatically ignore all F401 errors within the `if TYPE_CHECKING:` block?

**Comment by pjdelport** [comment] 2017-09-15 10:37
This happens in pyflakes 1.5.0 (which flake8 still declares its dependency on), but is fixed in pyflakes 1.6.0.

If you installed pyflakes via flake8, you can just separately upgrade pyflakes to 1.6.0, and shouldn't run into this anymore.

**Comment by myint** [comment] 2017-09-16 23:20
I can reproduce this in version 1.6.0.

```
$ pyflakes foo.py
foo.py:3: 'my_module.test_class.MyClass' imported but unused
$ pyflakes --version
1.6.0
```

**Comment by henryJack** [comment] 2017-09-17 07:58
Yep. Issue persists in 1.6.0.

**Comment by pjdelport** [comment] 2017-09-17 15:15
I think that's because the `foo.py` example uses a string annotation, rather than a direct reference to `MyClass`

If you change `object: 'MyClass' = None` to `object: MyClass = None`, pyflakes 1.6.0 does not report any issue.

**Comment by henryJack** [comment] 2017-09-17 22:57
The reason you add quotes is to avoid the circular import error. If the imported class has a circular dependency, python will complain

**Comment by pjdelport** [comment] 2017-09-18 10:11
Hmm, it's probably a separate issue / feature then to have pyflakes interpret quoted annotations?

**Comment by henryJack** [comment] 2017-09-18 10:27
There are 3 solutions to this problem in increasing complexity:
- add the `#noqa` comment to offending import statements within the  `if TYPE_CHECKING` block.
- change `pyflakes` to automatically ignore all imports within the  `if TYPE_CHECKING` block.
- Get pyflakes to interpret the class inside the quoted type annotation and understand that a F401 is not needed.

Pycharm evaluates objects within a quotation for autocompletion, not sure if this is helpful but at least shows it's possible:

![image](https://user-images.githubusercontent.com/22593502/30538085-3b4ee0d8-9c64-11e7-8741-20240dd88b3a.png)

**Comment by sigmavirus24** [comment] 2017-09-18 20:08
> User add the #noqa comment to offending import statements within the if TYPE_CHECKING block.

Except that's not a PyFlakes solution, that's a Flake8 solution.

> Change pyflakes to automatically ignore all imports within the if TYPE_CHECKING block.

That sounds kind of unnecessary. How many variations will we need to support? `if TYPE_CHECKNING`, `if MYPY`, `if USING_ANNOTATIONS`, that seems kind of messy.

> Change pyflakes to interpret the class inside the quoted type annotation and understand that a F401 is not needed.

This almost seems to be the most reasonable to me. Especially if mypy, et. all, understand this as a proper type annotation.

**Comment by henryJack** [comment] 2017-09-19 07:20
@sigmavirus24  - yes, sorry, `option 1` should be:

- User to install flake8 then add the '# noqa' comment to offending import statements within the if TYPE_CHECKING block.

RE: `option 2`, a bit hacky but still, you could just ignore all conditional/indented imports.

RE: `option 3` is the ideal.

Does anyone have any ideas to get started with `option 3`? I wouldn't mind having a go at it. I have an interest in making a command line python tool so the experience would be good.

**Comment by taion** [comment] 2017-11-21 03:24
This is pretty closely related to #247 – just broadly teaching Pyflakes about different kinds of type annotations.

**Closed** 2017-11-25 19:47 UTC
