### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JelleZijlstra** [PyCQA/pyflakes#436] opened 2019-02-24 00:58 UTC
I had to pin [flake8-pyi](http://github.com/ambv/flake8-pyi) to an earlier version of pyflakes and flake8 because #422 (which has already been fixed—thanks!) broke some of our tests.

Would it be possible to create a new release with the fix for #422? This would help people who are using flake8-pyi to lint stub files upgrade to the newest flake8 and pyflakes.

**Comment by bryanforbes** [comment] 2019-02-24 02:06
Just to be clear, the new release would need to be a patch release (2.1.1) rather than a minor release (2.2.0) in order to be used with the latest release of flake8 since flake8 has pyflakes pinned to `<2.2.0,>=2.1.0`.

**Comment by asottile** [comment] 2019-02-24 02:38
#426 would likely require the next revision to be a minor release -- that said, I can make a release of flake8 which allows that version as well

before release we should probably try and address the regression in 2.1.0 for #421 and probably include the PR #435

**Comment by bitglue** [comment] 2019-02-28 19:30
I released a 2.1.1 with just the bugfixes in #420 and #423.

**Comment by mgedmin** [comment] 2019-07-08 13:14
How come `pyflakes/__init__.py` in git master still claims to be 2.1.0 and not 2.1.1?  A simple oversight?

**Comment by bitglue** [comment] 2019-07-13 22:40
yep, thanks, fixed.

**Comment by asottile** [comment] 2019-08-08 19:56
closing since 2.1.1 was released -- presumably we'll release a 2.2 at some point which contains the new features on master

**Closed by asottile** 2019-08-08 19:56 UTC
